import React, { Component } from 'react';
import './App.css';
import './About.css'
import Nav from './Nav'

class About extends Component {

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <Nav current='about'/>
          <video src='/wave.mov' autoPlay loop className="App-logo" alt="logo"/>
          <div style={{height: '60px'}}></div>
          <div className='title'>
            <span className='titleBlue'>&lt;</span>
            &nbsp;about&nbsp;
            <span className='titleBlue'> &#47;&gt;</span>
          </div>

          <div className='cardContainer'>


            <div className='bodyText right' style={{width: '30%'}}>
              <b style={{fontSize:'2.5em', fontWeight:'100'}}>what it is:</b><br/><br/>
              Accompani is a tool that provides users with harmonized versions of basic melodies. The user inputs a monophonic MusicXML file, and basic metadata to intiate the algorithm. We assume that the given melody only uses notes within the given key signature.
              <br/><br/>
              Accompani returns a MusicXML lead sheet with the original melody, chord symbols generated by the underlying machine learning model.
            </div>
            <div className='tint'>
              <img className='group' src='/group.jpeg' alt='group' />
            </div>


            <br/><br/><br/>



            <div className='tint'>
              <img className='group' src='/workflow.png' alt='setup' />
            </div>
            <div className='bodyText left'>
              <b style={{fontSize:'2.5em', fontWeight:'100'}}>how it works:</b><br/><br/>
              Our user-friendly interface takes in a MusicXML file, along with some basic metadata. The algorithm then performs the following tasks:
              <br/><br/>
              <b>1. Model Training:</b> After the user selects a genre, accompani builds a progression matrix, detailing the probability of any chord within the key signature moving to any other chord in the key signature.  This matrix is trained using a library of more than 3,000 songs in ChordPro format, which we parse chord by chord and use for model training.
              <br/><br/>
              <b>2. Input Parsing:</b> We use in the input XML to perform a note by note analysis of the given melody. Each note is matched with possible harmonizations, and then the algorithm is able to make decisions based on the matrix generated in step one.
              <br/><br/>
              <b>3. Progression Mapping:</b> Taking into account the harmonic rhythm preference set by the user, chords are matched and written as symbols to the new XML file before returning the file to the user on the front-end.
              <br/><br/>
              Because Accompani aims to get young or inexperienced musicians more excited about composing, the algorithm incorporates an element of randomness. More specifically, Accompani keeps it interesting by choosing the next chord in a progression based on probabilities on our progression matrix. This means a user may input the same melody twice and obtain two different output harmonizations.
            </div>

            <br/><br/><br/>


            <div className='bodyText right'>
              <b style={{fontSize:'2.5em', fontWeight:'100'}}>what it's for:</b><br/><br/>
               Accompani is built to be particularly useful for a few specific sets of users. Firstly, Accompani allows young or inexperienced musicians to experiment with the fundamentals of chordal structure and harmony. As students learn and begin to create their own compositions, Accompani provides them with an automatic music theory assistant, that let's them create more music, faster.
              <br/><br/>
              Secondly, Accompani caters to experienced composers who often need to perform mundane harmonization tasks by providing them the opportunity to automate these processes. We hope that these professionals can leverage Accompani to expedite their tedious workflows, allowing them to instead focus on more creative musical pursuits.
            </div>
            <div className='tint'>
              <img className='group' src='/group.jpg' alt='group' />
            </div>



            <br/><br/><br/>


            <div className='tint'>
              <img className='group' src='/setup.jpeg' alt='setup' />
            </div>
            <div className='bodyText left'>
              <b style={{fontSize:'2.5em', fontWeight:'100'}}>what's next</b>

              <br/><br/>
              <b>Training Data Growth:</b> Accompani's algorithm uses a progression matrix which is trained by real music.  By building the algorithm to train in real time, accompani will automatically improve itself with the addition of more data. We look forward to increasing the amount of available genres, and furthermore growing the existing data sets.
              <br/><br/>
              <b>Chord Vocabulary Growth:</b> Accompani currently handles all diatonic chords in a given major or minor key signture.  However, we look forward to increasing it's capabilities to venture out of a given key signature through modulations and tonicizations. The more musical gestures we can emulate, the more powerful the algorithm becomes.
            </div>

            <br/><br/><br/><br/>


            <div>
            <span style={{fontWeight:300}}>
              Northwestern University<br/>
              Interactive Audio Lab<br/>
              Prof. Bryan Pardo<br/>
              Spring, 2019
            </span>
            </div>


            <div style={{height:'100px'}}></div>

          </div>
        </header>
      </div>
    );
  }
}

export default About;
